Vagrant.configure("2") do |config|
    # Jammy - 22.04.5
    config.vm.box = "gyptazy/ubuntu22.04-desktop-arm64"
    config.vm.box_version = "1.0.0"
    config.vm.disk :disk, size: "65GB", primary: true
    #config.vm.box_version = "1.0.0"
    # config.vm.box = "starboard/ubuntu-arm64-22.04.5"
    # config.vm.box_version = "20221120.20.40.0"
    config.vm.box_download_insecure = true
    #config.vm.provision "shell", privileged: false, path: "rxm-k8s.sh"
    #config.vm.provision "shell", privileged: false, path: "rxm-docker.sh"
    config.vm.provider "vmware_desktop" do |v|
        v.vmx['displayName'] = 'rxm-labvm'
        v.memory = 8192
        v.cpus = 4
        v.ssh_info_public = true
        v.gui = true
        v.linked_clone = false
        v.vmx["ethernet0.virtualdev"] = "vmxnet3"
    end
end
